# Generated by Django 5.0.6 on 2024-06-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Datos', 'Datos'), ('Servicios', 'Servicios'), ('Software', 'Software'), ('Personal', 'Personal')], max_length=50)),
                ('confidencialidad', models.IntegerField()),
                ('integridad', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
            ],
        ),
    ]
